function A = A_fgrs(C,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%A_FGRS
%    A = A_FGRS(C,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 15:09:45

vx = sign(vx)*max(1e-8, vx);
vy = sign(vy)*max(1e-8, vy);


t2 = cos(varphi);
t3 = sin(varphi);
t4 = lr.*omegaB;
t5 = t4+vy;
t7 = vx+1.0e-8;
t10 = 1.0./t7;
t11 = t5.*t10;
t12 = atan(t11);
t13 = -delta+t12+1.0e-8;
t6 = tan(t13);
t8 = 1.0./t7.^2;
t9 = C.^2;
t14 = t6.^2;
t15 = t14+1.0;
t16 = t5.^2;
t17 = t8.*t16;
t18 = t17+1.0;
t19 = 1.0./t18;
t20 = 1.0./m;
t21 = sin(delta);
t22 = 1.0./Fz_f.^2;
t23 = 1.0./mu.^2;
t24 = R.*(2.0./3.0);
t25 = t24-1.0;
t26 = 1.0./Fz_f;
t27 = 1.0./mu;
t28 = t9.*t14;
t29 = 1.0./sqrt(t28);
t30 = R-2.0;
t31 = m.*omegaB;
t32 = C.*t5.*t8.*t15.*t19;
t33 = t5.*t6.*t8.*t9.*t15.*t19.*t26.*t27.*t29.*t30.*(1.0./3.0);
t52 = C.*t5.*t8.*t9.*t14.*t15.*t19.*t22.*t23.*t25.*(1.0./3.0);
t34 = t32+t33-t52;
t36 = lf.*omegaB;
t35 = -t36+vy;
t37 = cos(delta);
t38 = C.*t10.*t15.*t19;
t39 = t6.*t9.*t10.*t15.*t19.*t26.*t27.*t29.*t30.*(1.0./3.0);
t54 = C.*t9.*t10.*t14.*t15.*t19.*t22.*t23.*t25.*(1.0./3.0);
t40 = t38+t39-t54;
t41 = t10.*t35;
t42 = atan(t41);
t43 = t42+1.0e-8;
t44 = dirac(t43);
t45 = t35.^2;
t46 = t8.*t45;
t47 = t46+1.0;
t48 = 1.0./t47;
t49 = C.*lr.*t10.*t15.*t19;
t50 = lr.*t6.*t9.*t10.*t15.*t19.*t26.*t27.*t29.*t30.*(1.0./3.0);
t55 = C.*lr.*t9.*t10.*t14.*t15.*t19.*t22.*t23.*t25.*(1.0./3.0);
t51 = t49+t50-t55;
t53 = 1.0./Iz;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*vx-t2.*vy,t2.*vx-t3.*vy,0.0,0.0,0.0,0.0,t2,t3,0.0,-t20.*t21.*t34,t20.*(-t31+t34.*t37+Fz_r.*mu.*t8.*t35.*t44.*t48.*2.0),t53.*(lf.*t34.*t37-Fz_r.*lr.*mu.*t8.*t35.*t44.*t48.*2.0),-t3,t2,0.0,t20.*(t31+t21.*t40),-t20.*(t37.*t40+Fz_r.*mu.*t10.*t44.*t48.*2.0),-t53.*(lf.*t37.*t40-Fz_r.*lr.*mu.*t10.*t44.*t48.*2.0),0.0,0.0,1.0,t20.*(m.*vy+t21.*t51),-t20.*(m.*vx+t37.*t51-Fz_r.*lf.*mu.*t10.*t44.*t48.*2.0),-t53.*(lf.*t37.*t51+Fz_r.*lf.*lr.*mu.*t10.*t44.*t48.*2.0)],[6,6]);
