function B = B_fgrg(C,Flong,Fz_f,Iz,R,delta,lf,lr,m,mu,omegaB,vx,vy)
%B_FGRG
%    B = B_FGRG(C,FLONG,FZ_F,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 15:23:11

vx = sign(vx)*max(1e-8, vx);
vy = sign(vy)*max(1e-8, vy);

t2 = 1.0./m;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = vx+1.0e-8;
t8 = 1.0./t7;
t9 = t6.*t8;
t10 = atan(t9);
t11 = delta-t10;
t3 = tan(t11);
t4 = C.^2;
t12 = t3.^2;
t13 = t12+1.0;
t14 = cos(delta);
t15 = 1.0./Fz_f;
t16 = 1.0./mu;
t17 = t4.*t12;
t18 = R-2.0;
t19 = 1.0./Fz_f.^2;
t20 = 1.0./mu.^2;
t21 = R.*(2.0./3.0);
t22 = t21-1.0;
t23 = sin(delta);
t24 = C.*t4.*t12.*t13.*t19.*t20.*t22.*(1.0./3.0);
t25 = 1.0./sqrt(t17);
t26 = t3.*t4.*t13.*t15.*t16.*t18.*t25.*(1.0./3.0);
t33 = C.*t13;
t27 = t24+t26-t33;
t28 = sqrt(t17);
t29 = t15.*t16.*t18.*t28.*(1.0./3.0);
t30 = C.*t3.*t4.*t12.*t19.*t20.*t22.*(1.0./9.0);
t34 = C.*t3;
t31 = t29+t30-t34;
t32 = 1.0./Iz;
B = reshape([0.0,0.0,0.0,t2.*(t14+1.0),t2.*t23,lf.*t23.*t32,0.0,0.0,0.0,t2.*(-Flong.*t23+t14.*t31+t23.*t27),t2.*(Flong.*t14-t14.*t27+t23.*t31),t32.*(Flong.*lf.*t14-lf.*t14.*t27+lf.*t23.*t31)],[6,2]);
