function B = B_fgrs(C,Flong,Fz_f,Iz,R,delta,lf,lr,m,mu,omegaB,vx,vy)
%B_FGRS
%    B = B_FGRS(C,FLONG,FZ_F,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Nov-2018 21:22:54

t3 = lr.*omegaB;
t4 = t3+vy;
t5 = vx+1.0e-8;
t6 = 1.0./t5;
t7 = t4.*t6;
t8 = atan(t7);
t9 = delta-t8;
t2 = tan(t9);
t10 = t2.^2;
t11 = t10+1.0;
t12 = C.^2;
t13 = 1.0./Fz_f;
t14 = 1.0./mu;
t15 = t10.*t12;
t16 = R-2.0;
t17 = 1.0./Fz_f.^2;
t18 = 1.0./mu.^2;
t19 = R.*(2.0./3.0);
t20 = t19-1.0;
t21 = sqrt(t15);
t22 = sin(delta);
t23 = 1.0./m;
t24 = cos(delta);
t25 = C.*t2;
t26 = C.*t2.*t13.*t14.*t16.*t21.*(1.0./3.0);
t34 = C.*t2.*t10.*t12.*t17.*t18.*t20.*(1.0./9.0);
t27 = t25+t26-t34;
t28 = C.*t11;
t29 = C.*t11.*t13.*t14.*t16.*t21.*(1.0./3.0);
t30 = 1.0./sqrt(t15);
t31 = C.*t10.*t11.*t12.*t13.*t14.*t16.*t30.*(1.0./3.0);
t33 = C.*t10.*t11.*t12.*t17.*t18.*t20.*(1.0./3.0);
t32 = t28+t29+t31-t33;
t35 = 1.0./Iz;
B = reshape([0.0,0.0,0.0,-t23.*(Flong.*t22+t24.*t27+t22.*t32),t23.*(Flong.*t24-t22.*t27+t24.*t32),t35.*(Flong.*lf.*t24-lf.*t22.*t27+lf.*t24.*t32),0.0,0.0,0.0,t23.*(t24+1.0),t22.*t23,lf.*t22.*t35],[6,2]);
