function B = B_fgrs(C,Flong,Fz_f,Iz,R,delta,lf,lr,m,mu,omegaB,vx,vy)
%B_FGRS
%    B = B_FGRS(C,FLONG,FZ_F,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 23:23:07

t2 = 1.0./m;
t3 = cos(delta);
t4 = 1.0./vx;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = t4.*t6;
t8 = atan(t7);
t9 = delta-t8;
t10 = tan(t9);
t11 = C.^2;
t12 = t10.^2;
t13 = sin(delta);
t14 = 1.0./Fz_f.^2;
t15 = 1.0./mu.^2;
t16 = R.*(2.0./3.0);
t17 = t16-1.0;
t18 = t12+1.0;
t19 = 1.0./Fz_f;
t20 = 1.0./mu;
t21 = t11.*t12;
t22 = R-2.0;
t23 = sqrt(t21);
t24 = t19.*t20.*t22.*t23.*(1.0./3.0);
t25 = C.*t10.*t11.*t12.*t14.*t15.*t17.*(1.0./9.0);
t33 = C.*t10;
t26 = t24+t25-t33;
t27 = C.*t11.*t12.*t14.*t15.*t17.*t18.*(1.0./3.0);
t28 = 1.0./sqrt(t21);
t29 = t10.*t11.*t18.*t19.*t20.*t22.*t28.*(1.0./3.0);
t32 = C.*t18;
t30 = t27+t29-t32;
t31 = 1.0./Iz;
B = reshape([0.0,0.0,0.0,t2.*(t3+1.0),t2.*t13,lf.*t13.*t31,0.0,0.0,0.0,t2.*(-Flong.*t13+t3.*t26+t13.*t30),t2.*(Flong.*t3-t3.*t30+t13.*t26),t31.*(Flong.*lf.*t3-lf.*t3.*t30+lf.*t13.*t26)],[6,2]);
