function B = B_fgrg(C,Flong,Fz_f,Iz,R,delta,lf,lr,m,mu,omegaB,vx,vy)

B =[                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0;
                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0;
                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0;
     (cos(delta) + 1)/m,           (sin(delta)*((C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2*((2*R)/3 - 1)*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1))/(3*Fz_f^2*mu^2) - C*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1) + (C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1)*(R - 2))/(3*Fz_f*mu*(C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2))) + cos(delta)*(((C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2)*(R - 2))/(3*Fz_f*mu) - C*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000))) + (C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^3*((2*R)/3 - 1))/(9*Fz_f^2*mu^2)) - Flong*sin(delta))/m;
           sin(delta)/m,           (sin(delta)*(((C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2)*(R - 2))/(3*Fz_f*mu) - C*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000))) + (C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^3*((2*R)/3 - 1))/(9*Fz_f^2*mu^2)) - cos(delta)*((C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2*((2*R)/3 - 1)*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1))/(3*Fz_f^2*mu^2) - C*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1) + (C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1)*(R - 2))/(3*Fz_f*mu*(C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2))) + Flong*cos(delta))/m;
     (lf*sin(delta))/Iz, (lf*sin(delta)*(((C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2)*(R - 2))/(3*Fz_f*mu) - C*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000))) + (C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^3*((2*R)/3 - 1))/(9*Fz_f^2*mu^2)) - lf*cos(delta)*((C^3*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2*((2*R)/3 - 1)*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1))/(3*Fz_f^2*mu^2) - C*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1) + (C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))*(tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2 + 1)*(R - 2))/(3*Fz_f*mu*(C^2*tan(delta - atan((vy + lr*omegaB)/(vx + 1/100000000)))^2)^(1/2))) + Flong*lf*cos(delta))/Iz];
 
end
