function B = B_fsrg(Flong,Fz_f,Iz,delta,lf,lr,m,mu,omegaB,vx,vy)
%B_FSRG
%    B = B_FSRG(FLONG,FZ_F,IZ,DELTA,LF,LR,M,MU,OMEGAB,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 23:23:05

t2 = 1.0./m;
t3 = cos(delta);
t4 = 1.0./vx;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = t4.*t6;
t8 = atan(t7);
t9 = -delta+t8;
t10 = sin(delta);
t11 = dirac(t9);
t12 = sign(t9);
t13 = 1.0./Iz;
B = reshape([0.0,0.0,0.0,t2.*(t3+1.0),t2.*t10,lf.*t10.*t13,0.0,0.0,0.0,-t2.*(Flong.*t10-Fz_f.*mu.*t3.*t12+Fz_f.*mu.*t10.*t11.*2.0),t2.*(Flong.*t3+Fz_f.*mu.*t3.*t11.*2.0+Fz_f.*mu.*t10.*t12),t13.*(Flong.*lf.*t3+Fz_f.*lf.*mu.*t3.*t11.*2.0+Fz_f.*lf.*mu.*t10.*t12)],[6,2]);
