function B = B_fsrg(Flong,Fz_f,Iz,R,delta,lf,lr,m,mu,omegaB,vx,vy)
%B_FSRG
%    B = B_FSRG(FLONG,FZ_F,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Nov-2018 21:22:52

t2 = lr.*omegaB;
t3 = t2+vy;
t4 = vx+1.0e-8;
t5 = 1.0./t4;
t6 = t3.*t5;
t7 = atan(t6);
t8 = -delta+t7;
t9 = sin(delta);
t10 = 1.0./m;
t11 = cos(delta);
t12 = dirac(t8);
t13 = sign(t8);
t14 = 1.0./Iz;
B = reshape([0.0,0.0,0.0,-t10.*(Flong.*t9+Fz_f.*R.*mu.*t9.*t12.*2.0-Fz_f.*R.*mu.*t11.*t13),t10.*(Flong.*t11+Fz_f.*R.*mu.*t9.*t13+Fz_f.*R.*mu.*t11.*t12.*2.0),t14.*(Flong.*lf.*t11+Fz_f.*R.*lf.*mu.*t9.*t13+Fz_f.*R.*lf.*mu.*t11.*t12.*2.0),0.0,0.0,0.0,t10.*(t11+1.0),t9.*t10,lf.*t9.*t14],[6,2]);
