function C_el = getCel(X,Y,ax,ay,bx,by,cx,cy,dx,dy,theta)
%GETCEL
%    C_EL = GETCEL(X,Y,AX,AY,BX,BY,CX,CY,DX,DY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Nov-2018 16:44:15

t3 = theta.^2;
t4 = cy.*theta.*2.0;
t5 = dy.*t3.*3.0;
t2 = by+t4+t5;
t6 = t2.^2;
t7 = cx.*theta.*2.0;
t8 = dx.*t3.*3.0;
t9 = bx+t7+t8+1.0e-8;
t10 = 1.0./t9.^2;
t11 = t6.*t10;
t12 = t11+1.0;
t13 = 1.0./sqrt(t12);
t14 = 1.0./t9;
t15 = cy.*2.0;
t16 = dy.*theta.*6.0;
t17 = t15+t16;
t18 = cx.*2.0;
t19 = dx.*theta.*6.0;
t20 = t18+t19;
t21 = 1.0./t9.^3;
t22 = t2.*t10.*t17.*2.0-t6.*t20.*t21.*2.0;
t23 = 1.0./t12.^(3.0./2.0);
t24 = by.*theta;
t25 = cy.*t3;
t26 = dy.*t3.*theta;
t27 = -Y+ay+t24+t25+t26;
C_el = [-t13;-t2.*t13.*t14;t13.*(bx+t7+t8)+t6.*t13.*t14-t22.*t23.*(-X+ax+bx.*theta+cx.*t3+dx.*t3.*theta).*(1.0./2.0)+t13.*t14.*t17.*t27-t2.*t10.*t13.*t20.*t27-t2.*t14.*t22.*t23.*t27.*(1.0./2.0)];
