function C_ec = getCec(X,Y,ax,ay,bx,by,cx,cy,dx,dy,theta)
%GETCEC
%    C_EC = GETCEC(X,Y,AX,AY,BX,BY,CX,CY,DX,DY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Nov-2018 16:44:14

t3 = theta.^2;
t4 = cy.*theta.*2.0;
t5 = dy.*t3.*3.0;
t2 = by+t4+t5;
t6 = cx.*theta.*2.0;
t7 = dx.*t3.*3.0;
t8 = bx+t6+t7+1.0e-8;
t9 = t2.^2;
t10 = 1.0./t8.^2;
t11 = t9.*t10;
t12 = t11+1.0;
t13 = 1.0./sqrt(t12);
t14 = 1.0./t8;
t15 = cy.*2.0;
t16 = dy.*theta.*6.0;
t17 = t15+t16;
t18 = cx.*2.0;
t19 = dx.*theta.*6.0;
t20 = t18+t19;
t21 = 1.0./t8.^3;
t22 = t2.*t10.*t17.*2.0-t9.*t20.*t21.*2.0;
t23 = 1.0./t12.^(3.0./2.0);
t24 = bx.*theta;
t25 = cx.*t3;
t26 = dx.*t3.*theta;
t27 = -X+ax+t24+t25+t26;
C_ec = [t2.*t13.*t14;-t13;t2.*t13-t22.*t23.*(-Y+ay+by.*theta+cy.*t3+dy.*t3.*theta).*(1.0./2.0)-t13.*t14.*t17.*t27-t2.*t13.*t14.*(bx+t6+t7)+t2.*t10.*t13.*t20.*t27+t2.*t14.*t22.*t23.*t27.*(1.0./2.0)];
