function Gamma_el = getGammaEl(X,Y,ax,ay,bx,by,cx,cy,dx,dy,theta)
%GETGAMMAEL
%    GAMMA_EL = GETGAMMAEL(X,Y,AX,AY,BX,BY,CX,CY,DX,DY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Nov-2018 16:43:03

t2 = theta.^2;
t3 = cy.*theta.*2.0;
t4 = dy.*t2.*3.0;
t5 = by+t3+t4;
t6 = cx.*theta.*2.0;
t7 = dx.*t2.*3.0;
t8 = bx+t6+t7+1.0e-8;
t9 = t5.^2;
t10 = 1.0./t8.^2;
t11 = cy.*2.0;
t12 = dy.*theta.*6.0;
t13 = t11+t12;
t14 = t9.*t10;
t15 = t14+1.0;
t16 = cx.*2.0;
t17 = dx.*theta.*6.0;
t18 = t16+t17;
t19 = 1.0./t8.^3;
t24 = t5.*t10.*t13.*2.0;
t25 = t9.*t18.*t19.*2.0;
t20 = t24-t25;
t21 = 1.0./t15.^(3.0./2.0);
t22 = 1.0./t8;
t23 = 1.0./sqrt(t15);
t26 = t20.*t21.*(1.0./2.0);
t27 = t5.*t20.*t21.*t22.*(1.0./2.0);
t28 = t5.*t10.*t18.*t23;
t29 = t27+t28-t13.*t22.*t23;
t30 = bx.*theta;
t31 = cx.*t2;
t32 = dx.*t2.*theta;
t33 = -X+ax+t30+t31+t32;
t34 = by.*theta;
t35 = cy.*t2;
t36 = dy.*t2.*theta;
t37 = -Y+ay+t34+t35+t36;
t38 = t20.^2;
t39 = 1.0./t15.^(5.0./2.0);
t40 = t18.^2;
t41 = t13.^2;
t42 = t10.*t41.*2.0;
t43 = 1.0./t8.^4;
t44 = t9.*t40.*t43.*6.0;
t45 = dy.*t5.*t10.*1.2e1;
t46 = t42+t44+t45-dx.*t9.*t19.*1.2e1-t5.*t13.*t18.*t19.*8.0;
Gamma_el = reshape([0.0,0.0,t26,0.0,0.0,t29,t26,t29,t18.*t23-t21.*t33.*t46.*(1.0./2.0)+t33.*t38.*t39.*(3.0./4.0)-t20.*t21.*(bx+t6+t7)+dy.*t22.*t23.*t37.*6.0-t9.*t10.*t18.*t23.*2.0+t5.*t13.*t22.*t23.*3.0-t9.*t20.*t21.*t22-dx.*t5.*t10.*t23.*t37.*6.0-t10.*t13.*t18.*t23.*t37.*2.0-t13.*t20.*t21.*t22.*t37+t5.*t19.*t23.*t37.*t40.*2.0-t5.*t21.*t22.*t37.*t46.*(1.0./2.0)+t5.*t22.*t37.*t38.*t39.*(3.0./4.0)+t5.*t10.*t18.*t20.*t21.*t37],[3,3]);
