function statesdot = statesdot_fgrs(C,Flong,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT_FGRS
%    STATESDOT = STATESDOT_FGRS(C,FLONG,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 15:09:46

t2 = cos(varphi);
t3 = sin(varphi);
t4 = lr.*omegaB;
t5 = t4+vy;
t6 = vx+1.0e-8;
t7 = 1.0./t6;
t8 = t5.*t7;
t9 = atan(t8);
t10 = -delta+t9+1.0e-8;
t11 = tan(t10);
t12 = C.^2;
t13 = t11.^2;
t14 = 1.0./m;
t15 = cos(delta);
t16 = C.*t11;
t17 = 1.0./Fz_f;
t18 = 1.0./mu;
t19 = t12.*t13;
t20 = sqrt(t19);
t21 = R-2.0;
t22 = t17.*t18.*t20.*t21.*(1.0./3.0);
t23 = 1.0./Fz_f.^2;
t24 = 1.0./mu.^2;
t25 = R.*(2.0./3.0);
t26 = t25-1.0;
t29 = C.*t11.*t12.*t13.*t23.*t24.*t26.*(1.0./9.0);
t27 = t16+t22-t29;
t28 = sin(delta);
t30 = vy-lf.*omegaB;
t31 = t7.*t30;
t32 = atan(t31);
t33 = t32+1.0e-8;
t34 = sign(t33);
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t14.*(Flong+Flong.*t15+t27.*t28+m.*omegaB.*vy);-t14.*(-Flong.*t28+t15.*t27+Fz_r.*mu.*t34+m.*omegaB.*vx);(Flong.*lf.*t28-lf.*t15.*t27+Fz_r.*lr.*mu.*t34)./Iz];
