function statesdot = statesdot_fgrg(C,Flong,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT_FGRG
%    STATESDOT = STATESDOT_FGRG(C,FLONG,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 23:23:05


t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./vx;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = t4.*t6;
t8 = atan(t7);
t9 = delta-t8;
t10 = tan(t9);
t11 = C.^2;
t12 = t10.^2;
t13 = 1.0./m;
t14 = cos(delta);
t15 = 1.0./Fz_f;
t16 = 1.0./mu;
t17 = t11.*t12;
t18 = sqrt(t17);
t19 = R-2.0;
t20 = t15.*t16.*t18.*t19.*(1.0./3.0);
t21 = 1.0./Fz_f.^2;
t22 = 1.0./mu.^2;
t23 = R.*(2.0./3.0);
t24 = t23-1.0;
t25 = C.*t10.*t11.*t12.*t21.*t22.*t24.*(1.0./9.0);
t39 = C.*t10;
t26 = t20+t25-t39;
t27 = sin(delta);
t29 = lf.*omegaB;
t28 = -t29+vy;
t30 = t28.^2;
t31 = C.*t4.*t28;
t32 = 1.0./Fz_r;
t33 = 1.0./vx.^2;
t34 = t11.*t30.*t33;
t35 = sqrt(t34);
t36 = t16.*t19.*t32.*t35.*(1.0./3.0);
t37 = 1.0./Fz_r.^2;
t38 = 1.0./vx.^3;
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t13.*(Flong+Flong.*t14+t26.*t27+m.*omegaB.*vy);-t13.*(t31+t36-Flong.*t27+t14.*t26+m.*omegaB.*vx-C.*t11.*t22.*t24.*t28.*t30.*t37.*t38.*(1.0./9.0));(lr.*(t31+t36-C.*t11.*t22.*t24.*t28.*t30.*t37.*t38.*(1.0./9.0))+Flong.*lf.*t27-lf.*t14.*t26)./Iz];
