function statesdot = statesdot_fsrg(C,Flong,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT_FSRG
%    STATESDOT = STATESDOT_FSRG(C,FLONG,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 15:23:13

t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./m;
t5 = sin(delta);
t6 = vx+1.0e-8;
t7 = 1.0./t6;
t8 = lr.*omegaB;
t9 = t8+vy;
t10 = t7.*t9;
t11 = atan(t10);
t12 = -delta+t11;
t13 = sign(t12);
t14 = cos(delta);
t17 = lf.*omegaB;
t15 = -t17+vy;
t16 = C.^2;
t18 = t15.^2;
t19 = C.*t7.*t15;
t20 = 1.0./Fz_r;
t21 = 1.0./mu;
t22 = R-2.0;
t23 = 1.0./t6.^2;
t24 = t16.*t18.*t23;
t25 = sqrt(t24);
t26 = t20.*t21.*t22.*t25.*(1.0./3.0);
t27 = 1.0./Fz_r.^2;
t28 = 1.0./mu.^2;
t29 = R.*(2.0./3.0);
t30 = t29-1.0;
t31 = 1.0./t6.^3;
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t4.*(Flong+Flong.*t14+m.*omegaB.*vy+Fz_f.*mu.*t5.*t13);-t4.*(t19+t26-Flong.*t5+m.*omegaB.*vx+Fz_f.*mu.*t13.*t14-C.*t15.*t16.*t18.*t27.*t28.*t30.*t31.*(1.0./9.0));(lr.*(t19+t26-C.*t15.*t16.*t18.*t27.*t28.*t30.*t31.*(1.0./9.0))+Flong.*lf.*t5-Fz_f.*lf.*mu.*t13.*t14)./Iz];
