function statesdot = statesdot_fgrg(C,Flong,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT_FGRG
%    STATESDOT = STATESDOT_FGRG(C,FLONG,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 14:18:41

t2 = cos(varphi);
t3 = sin(varphi);
t4 = lr.*omegaB;
t5 = t4+vy;
t6 = vx+1.0e-8;
t7 = 1.0./t6;
t8 = t5.*t7;
t9 = atan(t8);
t10 = delta-t9;
t11 = tan(t10);
t12 = C.^2;
t13 = t11.^2;
t14 = 1.0./m;
t15 = cos(delta);
t16 = 1.0./Fz_f;
t17 = 1.0./mu;
t18 = t12.*t13;
t19 = sqrt(t18);
t20 = R-2.0;
t21 = t16.*t17.*t19.*t20.*(1.0./3.0);
t22 = 1.0./Fz_f.^2;
t23 = 1.0./mu.^2;
t24 = R.*(2.0./3.0);
t25 = t24-1.0;
t26 = C.*t11.*t12.*t13.*t22.*t23.*t25.*(1.0./9.0);
t40 = C.*t11;
t27 = t21+t26-t40;
t28 = sin(delta);
t30 = lf.*omegaB;
t29 = -t30+vy;
t31 = t29.^2;
t32 = C.*t7.*t29;
t33 = 1.0./Fz_r;
t34 = 1.0./t6.^2;
t35 = t12.*t31.*t34;
t36 = sqrt(t35);
t37 = t17.*t20.*t33.*t36.*(1.0./3.0);
t38 = 1.0./Fz_r.^2;
t39 = 1.0./t6.^3;
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t14.*(Flong+Flong.*t15+t27.*t28+m.*omegaB.*vy);-t14.*(t32+t37-Flong.*t28+t15.*t27+m.*omegaB.*vx-C.*t12.*t23.*t25.*t29.*t31.*t38.*t39.*(1.0./9.0));(lr.*(t32+t37-C.*t12.*t23.*t25.*t29.*t31.*t38.*t39.*(1.0./9.0))+Flong.*lf.*t28-lf.*t15.*t27)./Iz];
