function statesdot = statesdot(Flong,Fz_f,Fz_r,Iz,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT
%    STATESDOT = STATESDOT(FLONG,FZ_F,FZ_R,IZ,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 23:17:40

t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./m;
t5 = sin(delta);
t6 = 1.0./vx;
t7 = lr.*omegaB;
t8 = t7+vy;
t9 = t6.*t8;
t10 = atan(t9);
t11 = -delta+t10;
t12 = sign(t11);
t13 = cos(delta);
t14 = vy-lf.*omegaB;
t15 = t6.*t14;
t16 = atan(t15);
t17 = sign(t16);
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t4.*(Flong+Flong.*t13+m.*omegaB.*vy+Fz_f.*mu.*t5.*t12);-t4.*(-Flong.*t5+Fz_r.*mu.*t17+m.*omegaB.*vx+Fz_f.*mu.*t12.*t13);(Flong.*lf.*t5+Fz_r.*lr.*mu.*t17-Fz_f.*lf.*mu.*t12.*t13)./Iz];
