function statesdot = statesdot_fsrs(Flong,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%STATESDOT_FSRS
%    STATESDOT = STATESDOT_FSRS(FLONG,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Nov-2018 14:12:33

t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./m;
t5 = sin(delta);
t6 = vx+1.0e-8;
t7 = 1.0./t6;
t8 = lf.*omegaB;
t9 = t8+vy;
t10 = t7.*t9;
t11 = atan(t10);
t12 = -delta+t11;
t13 = sign(t12);
t14 = cos(delta);
t15 = vy-lr.*omegaB;
t16 = t7.*t15;
t17 = atan(t16);
t18 = sign(t17);
statesdot = [t2.*vx-t3.*vy;t3.*vx+t2.*vy;omegaB;t4.*(Flong+Flong.*t14+Fz_f.*R.*mu.*t5.*t13);-t4.*(-Flong.*t5+Fz_r.*R.*mu.*t18+Fz_f.*R.*mu.*t13.*t14);(Flong.*lf.*t5+Fz_r.*R.*lr.*mu.*t18-Fz_f.*R.*lf.*mu.*t13.*t14)./Iz];
