function A = A_fsrns(C,Fz_f,Fz_r,Iz,R,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%A_FSRNS
%    A = A_FSRNS(C,FZ_F,FZ_R,IZ,R,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 20:36:52

t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./vx.^2;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = 1.0./m;
t8 = 1.0./vx;
t9 = t6.*t8;
t10 = atan(t9);
t11 = -delta+t10;
t12 = dirac(t11);
t13 = sin(delta);
t14 = t6.^2;
t15 = t4.*t14;
t16 = t15+1.0;
t17 = 1.0./t16;
t18 = m.*omegaB;
t19 = C.^2;
t22 = lf.*omegaB;
t20 = -t22+vy;
t21 = t20.^2;
t23 = cos(delta);
t24 = 1.0./Fz_r.^2;
t25 = 1.0./mu.^2;
t26 = 1.0./vx.^3;
t27 = R.*(2.0./3.0);
t28 = t27-1.0;
t29 = 1.0./Fz_r;
t30 = 1.0./mu;
t31 = R-2.0;
t32 = t4.*t19.*t21;
t33 = 1.0./sqrt(t32);
t34 = C.*t4.*t20;
t35 = 1.0./vx.^4;
t36 = t19.*t21.*t26.*t29.*t30.*t31.*t33.*(1.0./3.0);
t37 = 1.0./Iz;
t38 = C.*t8;
t39 = vy.*2.0;
t40 = t39-lf.*omegaB.*2.0;
t41 = t4.*t19.*t29.*t30.*t31.*t33.*t40.*(1.0./6.0);
t42 = C.*lf.*t19.*t21.*t24.*t25.*t26.*t28.*(1.0./3.0);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*vx-t2.*vy,t2.*vx-t3.*vy,0.0,0.0,0.0,0.0,t2,t3,0.0,Fz_f.*mu.*t4.*t6.*t7.*t12.*t13.*t17.*-2.0,t7.*(-t18+t34+t36+Fz_f.*mu.*t4.*t6.*t12.*t17.*t23.*2.0-C.*t19.*t20.*t21.*t24.*t25.*t28.*t35.*(1.0./3.0)),-t37.*(lr.*(t34+t36-C.*t19.*t20.*t21.*t24.*t25.*t28.*t35.*(1.0./3.0))-Fz_f.*lf.*mu.*t4.*t6.*t12.*t17.*t23.*2.0),-t3,t2,0.0,t7.*(t18+Fz_f.*mu.*t8.*t12.*t13.*t17.*2.0),-t7.*(t38+t41+Fz_f.*mu.*t8.*t12.*t17.*t23.*2.0-C.*t19.*t21.*t24.*t25.*t26.*t28.*(1.0./3.0)),t37.*(lr.*(t38+t41-C.*t19.*t21.*t24.*t25.*t26.*t28.*(1.0./3.0))-Fz_f.*lf.*mu.*t8.*t12.*t17.*t23.*2.0),0.0,0.0,1.0,t7.*(m.*vy+Fz_f.*lr.*mu.*t8.*t12.*t13.*t17.*2.0),-t7.*(t42+m.*vx-C.*lf.*t8+Fz_f.*lr.*mu.*t8.*t12.*t17.*t23.*2.0-lf.*t4.*t19.*t20.*t29.*t30.*t31.*t33.*(1.0./3.0)),-t37.*(lr.*(-t42+C.*lf.*t8+lf.*t4.*t19.*t20.*t29.*t30.*t31.*t33.*(1.0./3.0))+Fz_f.*lf.*lr.*mu.*t8.*t12.*t17.*t23.*2.0)],[6,6]);
