function A = A_fsrs(Fz_f,Fz_r,Iz,delta,lf,lr,m,mu,omegaB,varphi,vx,vy)
%A_FSRS
%    A = A_FSRS(FZ_F,FZ_R,IZ,DELTA,LF,LR,M,MU,OMEGAB,VARPHI,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 20:36:54

t2 = cos(varphi);
t3 = sin(varphi);
t4 = 1.0./vx.^2;
t5 = lr.*omegaB;
t6 = t5+vy;
t7 = 1.0./m;
t8 = 1.0./vx;
t9 = t6.*t8;
t10 = atan(t9);
t11 = -delta+t10;
t12 = dirac(t11);
t13 = sin(delta);
t14 = t6.^2;
t15 = t4.*t14;
t16 = t15+1.0;
t17 = 1.0./t16;
t18 = m.*omegaB;
t20 = lf.*omegaB;
t19 = -t20+vy;
t21 = t8.*t19;
t22 = atan(t21);
t23 = dirac(t22);
t24 = t19.^2;
t25 = t4.*t24;
t26 = t25+1.0;
t27 = 1.0./t26;
t28 = cos(delta);
t29 = 1.0./Iz;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*vx-t2.*vy,t2.*vx-t3.*vy,0.0,0.0,0.0,0.0,t2,t3,0.0,Fz_f.*mu.*t4.*t6.*t7.*t12.*t13.*t17.*-2.0,t7.*(-t18+Fz_r.*mu.*t4.*t19.*t23.*t27.*2.0+Fz_f.*mu.*t4.*t6.*t12.*t17.*t28.*2.0),-t29.*(Fz_r.*lr.*mu.*t4.*t19.*t23.*t27.*2.0-Fz_f.*lf.*mu.*t4.*t6.*t12.*t17.*t28.*2.0),-t3,t2,0.0,t7.*(t18+Fz_f.*mu.*t8.*t12.*t13.*t17.*2.0),-t7.*(Fz_r.*mu.*t8.*t23.*t27.*2.0+Fz_f.*mu.*t8.*t12.*t17.*t28.*2.0),t29.*(Fz_r.*lr.*mu.*t8.*t23.*t27.*2.0-Fz_f.*lf.*mu.*t8.*t12.*t17.*t28.*2.0),0.0,0.0,1.0,t7.*(m.*vy+Fz_f.*lr.*mu.*t8.*t12.*t13.*t17.*2.0),-t7.*(m.*vx-Fz_r.*lf.*mu.*t8.*t23.*t27.*2.0+Fz_f.*lr.*mu.*t8.*t12.*t17.*t28.*2.0),-t29.*(Fz_r.*lf.*lr.*mu.*t8.*t23.*t27.*2.0+Fz_f.*lf.*lr.*mu.*t8.*t12.*t17.*t28.*2.0)],[6,6]);
