function C_el = getCel(X,Y,ax,ay,bx,by,cx,cy,dx,dy,theta)
%GETCEL
%    C_EL = GETCEL(X,Y,AX,AY,BX,BY,CX,CY,DX,DY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Nov-2018 19:11:12

t3 = theta.^2;
t4 = cy.*theta.*2.0;
t5 = dy.*t3.*3.0;
t2 = by+t4+t5;
t6 = t2.^2;
t7 = cx.*theta.*2.0;
t8 = dx.*t3.*3.0;
t9 = bx+t7+t8+1.0e-8;
t10 = 1.0./t9.^2;
t11 = t6.*t10;
t12 = t11+1.0;
t13 = 1.0./sqrt(t12);
t14 = bx.*theta;
t15 = cx.*t3;
t16 = dx.*t3.*theta;
t17 = -X+ax+t14+t15+t16;
t18 = t13.*t17;
t19 = 1.0./t9;
t20 = by.*theta;
t21 = cy.*t3;
t22 = dy.*t3.*theta;
t23 = -Y+ay+t20+t21+t22;
t24 = t2.*t13.*t19.*t23;
t25 = t18+t24;
t26 = cy.*2.0;
t27 = dy.*theta.*6.0;
t28 = t26+t27;
t29 = cx.*2.0;
t30 = dx.*theta.*6.0;
t31 = t29+t30;
t32 = 1.0./t9.^3;
t33 = t2.*t10.*t28.*2.0-t6.*t31.*t32.*2.0;
t34 = 1.0./t12.^(3.0./2.0);
C_el = [t13.*t25.*-2.0;t2.*t13.*t19.*t25.*-2.0;t25.*(t13.*(bx+t7+t8)+t6.*t13.*t19-t17.*t33.*t34.*(1.0./2.0)+t13.*t19.*t23.*t28-t2.*t10.*t13.*t23.*t31-t2.*t19.*t23.*t33.*t34.*(1.0./2.0)).*2.0];
